#!/usr/bin/env python3

import sys
import re
import argparse

urlre = re.compile(r'\[(.+?)\]\(.+?\)')

def convert_char(char: str) -> str:
    cc = ord(char)
    if cc == 0xa or cc == 0xd:
        return chr(0xd)
    if cc >= 0x20 and cc < 0x41:
        return chr(cc)
    if cc > 0x40 and cc <= 0x5a:
        return chr(cc + 0x20)
    if cc == 0x60:
        return "'"
    if cc > 0x60 and cc <= 0x7a:
        return chr(cc - 0x20)
    if cc in (0x5b, 0x5d, 0x60):
        return chr(cc)
    return chr(0x7f)

def convert_line(line: str) -> str:
    return ''.join([convert_char(x) for x in line])

def convert(args: argparse.Namespace):
    with open(args.file[0], 'r', encoding='ascii') as inpf:
        for line in inpf:
            line = urlre.sub('\\1', line)
            sys.stdout.write(convert_line(line) + ('\n' if args.test else ''))

if __name__ == '__main__':
    argp = argparse.ArgumentParser('petconv', description='Converts ASCII MarkDown to PETSCII')
    argp.add_argument('--test', '-t', action="store_true", help="add linefeed for cli testing")
    argp.add_argument('file', nargs=1, help="the file to convert")
    argp.parse_args()
    
    args = argp.parse_args()

    convert(args)
